name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.x'

      - name: Instalar dependências
        run: flutter pub get

      - name: Verificar formatação do código
        run: dart format --output=none --set-exit-if-changed .

      - name: Análise estática
        run: flutter analyze

      - name: Executar testes
        run: flutter test

      - name: Build do aplicativo
        run: flutter build apk --debug
